### ISSUE TITLE
Approve and Send disabled

### ISSUE THREAD

**Issue by katopz** [hop-protocol/v2-monorepo#1]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/97060/221088115-55477bcd-e7f6-4eca-b09d-42ed9e2af0e5.png">

Why `Approve` and `Send` are disabled?
Can I have some error message or something user can understand what's going on please?

**Comment by miguelmota** [comment]
Hi, please submit UI issues to [UI repo here](https://github.com/hop-protocol/hop/issues) with screenshots of console and we'll take a look. Thanks
